version: 2.1

branches:
  only:
    - dev

jobs:
  build:
    docker:
      - image: cimg/base:current
    resource_class: csabca83/defaultk8s
    steps:
      - run: echo "Hi I'm on a Container Runner!"

workflows:
  build-workflow:
    jobs:
      - build:
          filters:
            branches:
              only:
                - dev
#
